version: "3"

services:
  users-db:
    container_name: users-db
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    healthcheck :
      test: [ "CMD", "pg_isready", "-q", "-d", "users", "-U", "postgres" ]
      interval : 5s
      timeout : 5s
      retries : 5

  authentication-service:
   container_name: authentication-service
   image: ct-iot-authentication-service:dev
   ports:
     - "8001:8001"
   environment:
     - SENTRY_TRACES_SAMPLE_RATE=1.0
     - SENTRY_PROFILES_SAMPLE_RATE=0.5
     - SENTRY_SAMPLE_RATE=50
     - ENVIRONMENT=test
     - LOG_LEVEL=DEBUG
     - SERVICE_NAME=authentication-service
     - UVICORN_PORT=8001
     - JWT_SECRET=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
     - JWT_EXPIRY_SECONDS=3600
   depends_on:
     users-db:
       condition: service_healthy
