apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullname" . }}-config
  labels:
    app: ct-iot
data:
  sentryTracesSampleRate: {{ .Values.image.env.sentryTracesSampleRate | quote }}
  sentryProfilesSampleRate: {{ .Values.image.env.sentryProfilesSampleRate | quote }}
  sentrySampleRate: {{ .Values.image.env.sentrySampleRate | quote }}
  environment: {{ .Values.image.env.environment | quote }}
  logLevel: {{ .Values.image.env.logLevel | quote }}
  serviceName: {{ .Values.image.env.serviceName | quote }}
  uvicornPort: {{ .Values.image.env.uvicornPort | quote }}
  queueProtocol: {{ .Values.image.env.queueProtocol | quote }}
  queueHost: {{ .Values.image.env.queueHost | quote }}
  queuePorts: {{ .Values.image.env.queuePorts | quote }}
  queueAcks: {{ .Values.image.env.queueAcks | quote }}
  queuePollWaitSeconds: {{ .Values.image.env.queuePollWaitSeconds | quote }}
  queueTopicName: {{ .Values.image.env.queueTopicName | quote }}
  queueGroupId: {{ .Values.image.env.queueGroupId | quote }}
  emailAccountVerificationType: {{ .Values.image.env.emailAccountVerificationType | quote }}
  albUrl: {{ .Values.image.env.albUrl | quote }}
  authServiceUrl: {{ .Values.image.env.authServiceUrl | quote }}