{{- $files := .Files }}
{{- $path := "secrets-decrypted/credentials.yaml.dec"}}
{{- $secretData := $files.Get $path | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
  labels:
    app: ct-iot
type: Opaque
data:
{{- range $name, $secret := ($secretData) }}
  {{ $name }}: {{ $secret | toString | b64enc | quote }}
{{- end }}
