@startuml
'https://plantuml.com/activity-diagram-beta

title Confirm Account Activity Diagram

:Request;
note
URI=/api/signup
Method=POST
Request={
    "username": "foo@example.com",
    "password": "bar",
    "first_name": "Foo",
    "last_name": "Bar",
}
end note

:User Service;
split

:Response;
skinparam ActivityDiamondBackgroundColor orchid
if (VALIDATION_ERRORS?) then (no)
    #limegreen:201 - Success;
    kill;
else (yes)
    split
        #tomato:400 - Invalid Request;
        kill;
    split again
        #tomato:409 - User Exists;
        kill;
    split again
        #tomato:500 - Server Error;
        kill;
    end split
endif

split again
:Email Queue (Kafka);
note
{
    "username": "foo@example.com",
    "email_type": "CONFIRM_ACCOUNT_VERIFICATION",
}
end note

:Email Service;
kill;
end split

@enduml
