@startuml
'https://plantuml.com/activity-diagram-beta

title User Details Activity Diagram

:Request;
note
URI=/api/user-details
Method=POST
Request={
    "user_id": "9b15c498-626b-4647-ab77-d22ebae4c0fc",
}
end note

:User Service;

:Request;
note
URI=/api/jwt/authentication
Method=GET
Header={
    "auth-token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
    .eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG
    9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0
    .KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30"
end note

:Authentication Service;

skinparam ActivityDiamondBackgroundColor orchid
if (JWT Errors?) then (true)
    #tomato:401 - Unauthorised;
    kill;
else (false)
    #limegreen:200 - Success;
    kill;
endif

@enduml
