name: Build, Lint and Test

on:
  push:
    branches-ignore: [ "main" ]

jobs:
  env-vars:
    runs-on: ubuntu-latest
    outputs:
      POETRY_VERSION: ${{ steps.get-env-vars.outputs.POETRY_VERSION }}
      PYTHON_VERSION: ${{ steps.get-env-vars.outputs.PYTHON_VERSION }}
      AWS_REGION: ${{ steps.get-env-vars.outputs.AWS_REGION }}
      SENTRY_TRACES_SAMPLE_RATE: ${{ steps.get-env-vars.outputs.SENTRY_TRACES_SAMPLE_RATE }}
      SENTRY_PROFILES_SAMPLE_RATE: ${{ steps.get-env-vars.outputs.SENTRY_PROFILES_SAMPLE_RATE }}
      SENTRY_SAMPLE_RATE: ${{ steps.get-env-vars.outputs.SENTRY_SAMPLE_RATE }}
#      FIRST_NAME: ${{ steps.get-env.outputs.FIRST_NAME }}
#      USERNAME: ${{ steps.get-env.outputs.USERNAME }}
#      SERVICE_NAME: ${{ steps.get-env.outputs.SERVICE_NAME }}
#      LOG_LEVEL: ${{ steps.get-env.outputs.LOG_LEVEL }}
#      ENVIRONMENT: ${{ steps.get-env.outputs.ENVIRONMENT }}
#      APP_HOST: ${{ steps.get-env.outputs.APP_HOST }}
#      UVICORN_PORT: ${{ steps.get-env.outputs.UVICORN_PORT }}
#      JWT_SECRET: ${{ steps.get-env.outputs.JWT_SECRET }}
#      JWT_EXPIRY_SECONDS: ${{ steps.get-env.outputs.JWT_EXPIRY_SECONDS }}
#      QUEUE_PROTOCOL: ${{ steps.get-env.outputs.QUEUE_PROTOCOL }}
#      QUEUE_HOST: ${{ steps.get-env.outputs.QUEUE_HOST }}
#      QUEUE_PORTS: ${{ steps.get-env.outputs.QUEUE_PORTS }}
#      QUEUE_ACKS: ${{ steps.get-env.outputs.QUEUE_ACKS }}
#      QUEUE_POLL_WAIT_SECONDS: ${{ steps.get-env.outputs.QUEUE_POLL_WAIT_SECONDS }}
#      QUEUE_TOPIC_NAME: ${{ steps.get-env.outputs.QUEUE_TOPIC_NAME }}
#      QUEUE_GROUP_ID: ${{ steps.get-env.outputs.QUEUE_GROUP_ID }}
#      AUTH_SERVICE_ENDPOINT: ${{ steps.get-env.outputs.AUTH_SERVICE_ENDPOINT }}
#      USER_SERVICE_ENDPOINT: ${{ steps.get-env.outputs.USER_SERVICE_ENDPOINT }}
#      DB_HOST: ${{ steps.get-env.outputs.DB_HOST }}
#      DB_PORT: ${{ steps.get-env.outputs.DB_PORT }}
#      DB_USERNAME: ${{ steps.get-env.outputs.DB_USERNAME }}
#      DB_PASSWORD: ${{ steps.get-env.outputs.DB_PASSWORD }}
#      DB_NAME: ${{ steps.get-env.outputs.DB_NAME }}
#      JWT_SECRET_CONFIRM_ACCOUNT: ${{ steps.get-env.outputs.JWT_SECRET_CONFIRM_ACCOUNT }}
#      JWT_EXPIRY_SECONDS_CONFIRM_ACCOUNT: ${{ steps.get-env.outputs.JWT_EXPIRY_SECONDS_CONFIRM_ACCOUNT }}

    steps:
      - name: get environment variables
        id: get-env-vars
        run: |
          echo "POETRY_VERSION=1.7.1" >> $GITHUB_OUTPUT
          echo "PYTHON_VERSION=3.11.9" >> $GITHUB_OUTPUT
          echo "AWS_REGION=eu-west-2" >> $GITHUB_OUTPUT
          echo "SENTRY_TRACES_SAMPLE_RATE=1.0" >> $GITHUB_OUTPUT
          echo "SENTRY_PROFILES_SAMPLE_RATE=0.5" >> $GITHUB_OUTPUT
          echo "SENTRY_SAMPLE_RATE=50" >> $GITHUB_OUTPUT
          echo "FIRST_NAME=Foo" >> $GITHUB_OUTPUT
          echo "USERNAME=foo@example.com" >> $GITHUB_OUTPUT
          echo "SERVICE_NAME=user-service" >> $GITHUB_OUTPUT
          echo "LOG_LEVEL=DEBUG" >> $GITHUB_OUTPUT
          echo "ENVIRONMENT=test" >> $GITHUB_OUTPUT
          echo "APP_HOST=localhost" >> $GITHUB_OUTPUT
          echo "UVICORN_PORT=8002" >> $GITHUB_OUTPUT
          echo "JWT_SECRET=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789" >> $GITHUB_OUTPUT
          echo "JWT_EXPIRY_SECONDS=3600" >> $GITHUB_OUTPUT
          echo "QUEUE_PROTOCOL=PLAINTEXT" >> $GITHUB_OUTPUT
          echo "QUEUE_HOST=localhost" >> $GITHUB_OUTPUT
          echo "QUEUE_PORTS=9092,9093,9094" >> $GITHUB_OUTPUT
          echo "QUEUE_ACKS=all" >> $GITHUB_OUTPUT
          echo "QUEUE_POLL_WAIT_SECONDS=1" >> $GITHUB_OUTPUT
          echo "QUEUE_TOPIC_NAME=email-topic" >> $GITHUB_OUTPUT
          echo "QUEUE_GROUP_ID=email-topic-group" >> $GITHUB_OUTPUT
          echo "AUTH_SERVICE_ENDPOINT=http://localhost:8001" >> $GITHUB_OUTPUT
          echo "USER_SERVICE_ENDPOINT=http://localhost:8002" >> $GITHUB_OUTPUT
          echo "DB_HOST=localhost" >> $GITHUB_OUTPUT
          echo "DB_PORT=5432" >> $GITHUB_OUTPUT
          echo "DB_USERNAME=postgres" >> $GITHUB_OUTPUT
          echo "DB_PASSWORD=postgres" >> $GITHUB_OUTPUT
          echo "DB_NAME=users" >> $GITHUB_OUTPUT
          echo "JWT_SECRET_CONFIRM_ACCOUNT=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABC" >> $GITHUB_OUTPUT
          echo "JWT_EXPIRY_SECONDS_CONFIRM_ACCOUNT=3600" >> $GITHUB_OUTPUT

  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: actions checkout
        uses: actions/checkout@v4

      - name: check-version
        uses: darrylmorton/ct-continuous-workflows/.github/actions/check-version@v1
        with:
          package-manager: 'poetry'

  unit-tests:
    needs: [ check-version, env-vars ]
    uses: darrylmorton/ct-continuous-workflows/.github/workflows/python-test-unit.yml@v1
    with:
      poetry-version: ${{ needs.env-vars.outputs.POETRY_VERSION }}
      python-version: ${{ needs.env-vars.outputs.PYTHON_VERSION }}

  integration-tests:
    needs: [ check-version, env-vars ]
    uses: darrylmorton/ct-continuous-workflows/.github/workflows/python-test-integration.yml@v1
    with:
      poetry-version: ${{ needs.env-vars.outputs.POETRY_VERSION }}
      python-version: ${{ needs.env-vars.outputs.PYTHON_VERSION }}
      db-migrate-flag: 'true'
    secrets:
      gh-token: ${{ secrets.GITHUB_TOKEN }}